 
[[redirects]]
  from = "/blog/*"
  to = "https://llamalife.superblog.cloud/:splat"
  status = 200

[[redirects]]
  from = "/_elderjs/*"
  to = "https://llamalife.superblog.cloud/_elderjs/:splat"
  status = 200 
